'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Campers',
      [
        {
          title: '«База отдыха Чистые Пруды»',
          shelterCount: 4,
          camperCount: 12,
          eCoordinates: 37.01,
          wCoordinates: 59.45,
          data: `
          «База отдыха Чистые Пруды» находится в Гдове. Этот отель расположен в 6 км от центра города.
          Также для гостей в отеле: баня. Скучно не будет, ведь в отеле к услугам отдыхающих площадка для барбекю.
          Специально для автопутешественников организована бесплатная парковка.
          Персонал отеля говорит на русском.
          Любимца не придётся оставлять дома: разрешается проживание с питомцем. А ещё в распоряжении гостей индивидуальная регистрация заезда и отъезда.
          `,
          timeOpen: '08:00',
          timeClosed: '18:00',
          rate: 9,
          img: 'https://cdn-img.readytotrip.com/t/1024x768/extranet/a5/9d/a59d0a1806c50a4ed02d43c58c701890c6fa7923.jpeg',
          img2: 'https://cdn-img.readytotrip.com/t/1024x768/extranet/82/a3/82a3d9ebfefa22b599c9b1097105a27301a055a4.jpeg, https://cdn-img.readytotrip.com/t/1024x768/extranet/8f/b3/8fb34ae445da1f551c9cc68dacb07e68f8dc9245.jpeg',
          camperPrice: 1500,
          shelterPrice: 1000,
          place_type: 'роща',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'детская площадка, рыбалка, площадка для барбекю',
          communication: 'водопровод, свет, wifi, холодильник, кафе',
          sanitation: 'туалет, душ, баня',
          location: 'ул. Верхоляне-2',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в городе Гдов, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Раздолье»',
          shelterCount: 10,
          camperCount: 20,
          eCoordinates: 28.42,
          wCoordinates: 57.8,
          data: `Спортивно-туристический комплекс «Раздолье» расположен в тихом живописном месте в сосновом лесу на окраине города Псков. На территории есть полноценный кемпинг на 69 мест. В кемпинге присутствует подключение к электричеству, залив/слив чистой воды, возможность слива кассеты туалета, общественные душевые и туалеты, кухня и прачечная, отдельно оборудованная зона для гриля и барбекю.`,
          timeOpen: '08:00',
          timeClosed: '20:00',
          rate: 10,
          img: 'https://rvland.ru/wp-content/uploads/2020/01/rvland-razdolie-pskov-20.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2020/01/rvland-razdolie-pskov-22.jpg,https://rvland.ru/wp-content/uploads/2020/01/rvland-razdolie-pskov-12.jpg',
          camperPrice: 1500,
          shelterPrice: 1000,
          place_type: 'роща',
          seasonality: 'всесезонный',
          reservoir: 'озеро',
          entertainment: 'детская площадка, рыбалка, активный отдых',
          communication: 'водопровод, свет, кухня, прачечная',
          sanitation: 'туалет, душ',
          location: 'Ленинградское шоссе, д. 5А',
          pay_by_card: 'любой способ оплаты',
          addition: 'Кемпинг на природе в г.Псков, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Sky Ранчо»',
          shelterCount: 12,
          camperCount: 18,
          eCoordinates: 27.86,
          wCoordinates: 57.69,
          data: 'Кемпинг «Sky Ранчо» находится рядом с двумя небольшими озерами, по соседству с поселком Каменка (Псковская область). От города Псков пролегает прямая трасса расстоянием менее 30 км.',
          timeOpen: '08:00',
          timeClosed: '20:30',
          rate: 7,
          img: 'https://rvland.ru/wp-content/uploads/2021/07/rvland-skai-rancho-10.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2021/07/rvland-skai-rancho-3.jpg,https://rvland.ru/wp-content/uploads/2021/07/rvland-skai-rancho-11.jpg',
          camperPrice: 1500,
          shelterPrice: 1000,
          place_type: 'роща',
          seasonality: 'лето',
          reservoir: 'озеро',
          entertainment:
            'рыбалка, баня, горячие купельни, инвентарь для активных игр, мангальные зоны, беседки',
          communication: 'водопровод, свет, wifi',
          sanitation: 'туалет, душ, кухня',
          location: 'Печерский район',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в Псковская область, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Лисья Гора»',
          shelterCount: 15,
          camperCount: 10,
          eCoordinates: 31.18,
          wCoordinates: 58.42,
          data: `Кемпинг «Лисья Гора» находится всего в 10 километрах от Великого Новгорода в тихом живописном урочище, на берегу бывшего карьера. Кемпинг для расслабленного, либо активного отдыха, в зависимости от потребности. Можно просто отдыхать у воды, глядя на проплывающие облака. А можно заняться спортом, активными прогулками. Независимо от вашего выбора вы получите комфортное размещение с необходимыми удобствами.`,
          timeOpen: '08:00',
          timeClosed: '22:00',
          rate: 8,
          img: 'https://rvland.ru/wp-content/uploads/2024/01/rvland-1706481359.jpeg',
          img2: 'https://rvland.ru/wp-content/uploads/2024/01/rvland-1706481354.jpeg,https://rvland.ru/wp-content/uploads/2024/01/rvland-1706481356-1.jpeg',
          camperPrice: 1000,
          shelterPrice: 1500,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'озеро',
          entertainment:
            'прокат спортинвентаря, рыбалка, активный отдых, баня/сауна',
          communication: 'wi-fi, водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'Урочище Лисья Гора',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в Новгородская область, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Ранчо»',
          shelterCount: 1,
          camperCount: 10,
          eCoordinates: 39.2,
          wCoordinates: 54.74,
          data: `На берегу р.Пилис, окруженный старым лесом расположился кемпинг «Ранчо». Здесь вы можете отдохнуть от городского ритма и спокойно провести выходные.`,
          timeOpen: '06:00',
          timeClosed: '21:00',
          rate: 7,
          img: 'https://www.tatar-inform.ru/images/uploads/news/2023/6/8/7df9372c5202953c5620bdfa3a60f6c7.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2019/12/rvland-camping-rancho-04.jpg,https://rvland.ru/wp-content/uploads/2019/12/rvland-camping-rancho-01.jpg',
          camperPrice: 2000,
          shelterPrice: 100,
          place_type: 'поле',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment:
            'детская площадка, сбор грибов, рыбалка, контактный зоопарк',
          communication: 'связь, водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'деревня Чирьяково',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в Московская обл., Россия.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «В некотором царстве»',
          shelterCount: 1,
          camperCount: 24,
          eCoordinates: 39.84,
          wCoordinates: 54.73,
          data: `Кемпинг на 24 стояночных места для автодомов и караванов расположился рядом с развлекательным комплексом «В некотором царстве». В кемпинге есть электроэнергия, подвод чистой воды, слив грязной воды и кассеты биотуалета. Хозяйственный блок с душем, туалетом, стиральной машиной. Дрова и удобные беседки для постояльцев.`,
          timeOpen: '07:00',
          timeClosed: '22:00',
          rate: 9,
          img: 'https://rvland.ru/wp-content/uploads/2020/01/rvland-v-nekotorom-tsarstve-12.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2020/01/rvland-v-nekotorom-tsarstve-14.jpg,https://rvland.ru/wp-content/uploads/2020/01/rvland-v-nekotorom-tsarstve-18.jpg',
          camperPrice: 2500,
          shelterPrice: 1000,
          place_type: 'роща',
          seasonality: 'лето',
          reservoir: 'озеро',
          entertainment: 'рыбалка, дискотека',
          communication: 'водопровод, электричесво',
          sanitation: 'туалет, душ, прачечная',
          location: 'Трасса «Рязань–Клепики», в 13 км от города, г.Рязань',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в 13 км от города, г.Рязань, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Загородный отель «Парус»',
          shelterCount: 1,
          camperCount: 20,
          eCoordinates: 45.03,
          wCoordinates: 56.04,
          data: `Загородный отель «Парус»: комфортабельный отель, расположенный в исторической части старинного города Лысково. Находится он в удивительном месте, откуда открывается красивый вид на Волжские просторы, величественные Оленью и Лысую горы. На другом берегу расположена жемчужина Нижегородского Поволжья — Макарьевский Желтоводский монастырь.`,
          timeOpen: '07:00',
          timeClosed: '21:00',
          rate: 8,
          img: 'https://rvland.ru/wp-content/uploads/2021/12/rvland-zagorodnyi-otel-parus-5.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2021/12/rvland-zagorodnyi-otel-parus-10.jpg,https://rvland.ru/wp-content/uploads/2021/12/rvland-zagorodnyi-otel-parus-2.jpg',
          camperPrice: 1200,
          shelterPrice: 1000,
          place_type: 'роща',
          seasonality: 'лето',
          reservoir: 'нет',
          entertainment: 'детская площадка, бар',
          communication: 'водопровод, свет, wifi',
          sanitation: 'туалет, душ, баня',
          location: 'Ул. Нижняя Набережная д.2',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в Архангельская область, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Туристическая база «Серебряный ключ»',
          shelterCount: 12,
          camperCount: 21,
          eCoordinates: 41.8,
          wCoordinates: 63.42,
          data: 'Туристическая база «Серебряный ключ» находится в живописном месте, на месте возрожденного хутора Ключ. Окружающая первозданная природа способствует спокойному и созерцательному отдыху вдали от городской суеты. Переночевать на хуторе можно с относительным комфортом: есть и газовое, и печное отопление, электричество.',
          timeOpen: '07:30',
          timeClosed: '19:00',
          rate: 9,
          img: 'https://rvland.ru/wp-content/uploads/2021/08/rvland-baza-otdyha-chardym-dubrava-1.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2021/08/rvland-baza-otdyha-chardym-dubrava-4.jpg,https://rvland.ru/wp-content/uploads/2021/08/rvland-baza-otdyha-chardym-dubrava.jpg',
          camperPrice: 2000,
          shelterPrice: 1000,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'рыбалка, активный отдыхБ баня/сауна',
          communication: 'вода, электричество',
          sanitation: 'туалет, душ',
          location: 'хутор Ключ',
          pay_by_card: 'наличными',
          addition: 'Кемпинг на природе в Архангельская область, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'База отдыха «Чардым-Дубрава»',
          shelterCount: 14,
          camperCount: 16,
          eCoordinates: 41.55,
          wCoordinates: 63.55,
          data: 'База отдыха расположена в с. Чардым на берегу реки Волга. В 9 км. от федеральной трассы. Поэтому автотуристы могут заехать сюда и переночевать с комфортом. По близости расположены турбазы и базы отдыха, пристань и яхт-клуб. К услугам отдыхающих предоставляются апартаменты, домики на берегу. Можно разбить палатки или разместиться в автодоме.',
          timeOpen: '07:00',
          timeClosed: '18:00',
          rate: 7,
          img: 'https://rvland.ru/wp-content/uploads/2021/08/rvland-baza-otdyha-chardym-dubrava-6.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2021/08/rvland-baza-otdyha-chardym-dubrava-5.jpg,https://rvland.ru/wp-content/uploads/2021/08/rvland-baza-otdyha-chardym-dubrava-2.jpg',
          camperPrice: 1500,
          shelterPrice: 1000,
          place_type: 'роща',
          seasonality: 'лето',
          reservoir: 'озеро',
          entertainment: 'рыбалка, баня, бассейн',
          communication: 'wi-fi, водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'Усовский лесхоз, с.Чардым',
          pay_by_card: 'наличный, перевод',
          addition: 'Кемпинг на природе в Архангельская область, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Вокруг света»',
          shelterCount: 21,
          camperCount: 15,
          eCoordinates: 41.23,
          wCoordinates: 63.55,
          data: 'В июне 2021 г состоялось открытие кемпинга «Вокруг света». Владелец кемпинга — Саша Холодный, известный автопутешественник, автор и исполнитель множества серьезных экспедиций, в том числе «На буханке вокруг света». Если посчастливиться встретится с самим Александром, он расскажет вам о своем опыте путешествия по 120 странам мира на автомобилях. Знаменитая Буханка-кругосветчица так же находится на территории кемпинга.',
          timeOpen: '06:00',
          timeClosed: '22:00',
          rate: 9,
          img: 'https://rvland.ru/wp-content/uploads/2021/07/rvland-kemping-vokrug-sveta-8.jpg',
          img2: 'https://rvland.ru/wp-content/uploads/2021/07/rvland-kemping-vokrug-sveta-3.jpg,https://rvland.ru/wp-content/uploads/2021/07/rvland-kemping-vokrug-sveta-1.jpg',
          camperPrice: 1500,
          shelterPrice: 1000,
          place_type: 'поле',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'детская площадка, бассейн',
          communication: 'связь, свет, вода',
          sanitation: 'туалет',
          location: 'Овражная ул, д.Клубня',
          pay_by_card: 'есть',
          addition: 'Кемпинг на природе в Архангельская область, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Волга кемп',
          shelterCount: 23,
          camperCount: 4,
          eCoordinates: 49.8,
          wCoordinates: 50.8,
          data: 'Волга кемп идеально подходит для любителей активного отдыха на природе. Расположенный на берегу Волги, кемпинг предоставляет возможность для рыбной ловли, сплава по реке и просто отдыха на свежем воздухе. Волга кемп - отличный выбор для семейного отдыха, где можно насладиться природой и активными развлечениями.',
          timeOpen: '09:00',
          timeClosed: '17:30',
          rate: 8,
          img:
            'https://rvland.ru/thumbnail/?size=%3C400&src=https://rvland.ru/wp-content/uploads/2024/04/rvland-1711933818-2.jpeg',
            img2: 'https://rvland.ru/thumbnail/?size=%3C400&src=https://rvland.ru/wp-content/uploads/2024/04/rvland-1713725900.jpeg',
            img3: 'https://rvland.ru/thumbnail/?size=%3C400&src=https://rvland.ru/wp-content/uploads/2024/04/rvland-1713725902.jpeg',
          camperPrice: 2500,
          shelterPrice: 3000,
          place_type: 'роща',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'детская площадка, рыбалка, сплав',
          communication: 'водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'ул. Сосновая 44',
          pay_by_card: 'есть',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Автокемпинг',
          shelterCount: 4,
          camperCount: 24,
          eCoordinates: 39.28,
          wCoordinates: 51.77,
          data: 'Кемпинг находится на побережье реки Воронеж. Любимое место отдыха не только для местных жителей но и для приезжих.',
          timeOpen: '06:00',
          timeClosed: '22:00',
          rate: 6,
          img: 'https://www.superchalupy.cz/fotografie/115-15346.jpg',
          img2: 'https://sportishka.com/uploads/posts/2023-11/1701321313_sportishka-com-p-kemping-alushta-vkontakte-61.jpg',
          img3: 'https://turizm.pibig.info/uploads/posts/2023-10/1697656796_turizm-pibig-info-p-kempingi-v-katalonii-oboi-41.jpg',
          camperPrice: 1000,
          shelterPrice: 500,
          place_type: 'роща',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'рыбалка',
          communication: 'водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'городской округ г.Воронеж',
          pay_by_card: 'наличный',
          addition: 'Кемпинг на природе в Воронежской области, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Салют»',
          shelterCount: 20,
          camperCount: 20,
          eCoordinates: 39.86,
          wCoordinates: 42.42,
          data: `Кемпинг «Салют» находится всего в 5 километрах от Ростова-на-Дону в тихом живописном урочище. Кемпинг для расслабленного, либо активного отдыха, в зависимости от потребности. Можно просто отдыхать глядя на проплывающие облака. А можно заняться спортом, активными прогулками. Независимо от вашего выбора вы получите комфортное размещение с необходимыми удобствами.`,
          timeOpen: '00:00',
          timeClosed: '00:00',
          rate: 9,
          img:'https://avatars.mds.yandex.net/get-altay/1592431/2a00000173f6acf01f089418d5944e6e2a14/XXXL',
          img2: 'https://avatars.mds.yandex.net/get-altay/2761244/2a00000173f6acfa77f0c5ef42cb9c5c2fb7/XXXL',
          img3: 'https://avatars.mds.yandex.net/get-altay/2701558/2a0000017493410cc326077acb98c7829ecd/XXXL',
          camperPrice: 600,
          shelterPrice: 600,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'нет',
          entertainment: 'прокат спортинвентаря',
          communication: 'водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'хутов Каменный Брод',
          pay_by_card: 'наличный, перевод',
          addition: 'Кемпинг на природе в Ростовской области, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Енот»',
          shelterCount: 30,
          camperCount: 10,
          eCoordinates: 38.29,
          wCoordinates: 44.21,
          data: `Кемпинг «Енот» расположен на возвышенности, откуда открывается потрясающий вид на море и сосновый лес. На территории кемпинга есть несколько душевых и туалетов, а также умывальники, где можно помыть посуду и набрать воду.`,
          timeOpen: '06:00',
          timeClosed: '20:00',
          rate: 9,
          img:'https://avatars.mds.yandex.net/get-altay/10589039/2a0000018ae04b659d58d7c3c267211f4dec/XXXL',
          img2: 'https://avatars.mds.yandex.net/get-altay/6506385/2a0000018a1c66cc627cbb14292a8f88eb9a/XXXL',
          img3: 'https://avatars.mds.yandex.net/get-altay/4476499/2a000001822c3d761e188676510fc8b84914/XXXL',
          camperPrice: 1500,
          shelterPrice: 1500,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'море',
          entertainment: 'прокат спортинвентаря, детская площадка',
          communication: 'водопровод, свет, магазин',
          sanitation: 'туалет, душ',
          location: 'село Архипо-Осиповка',
          pay_by_card: 'любой вид оплаты',
          addition: 'Кемпинг на берегу моря в Краснодарском крае, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // 28
        {
          title: 'Кемпинг "Южное кочевье"',
          shelterCount: 20,
          camperCount: 20,
          eCoordinates: 35.02,
          wCoordinates: 44.83,
          data: `Шикарное место! Очень гостеприимные хозяйва, отличное место для отдыха с палатками. Посетители не остануться равнодушными к отдыху на свежем воздухе у моря!`,
          timeOpen: '06:00',
          timeClosed: '18:00',
          rate: 7,
          img:'https://i2.wp.com/russiakrasava.ru/wp-content/uploads/2017/06/%D0%90%D1%80%D1%85%D0%B8%D0%BF%D0%BE-%D0%9E%D1%81%D0%B8%D0%BF%D0%BE%D0%B2%D0%BA%D0%B8-5.jpg',
          img2: 'https://vsegda-pomnim.com/uploads/posts/2022-04/1651020964_21-vsegda-pomnim-com-p-kemping-na-more-foto-25.jpg',
          img3: 'https://images.saymedia-content.com/.image/t_share/MTk5NjMzNDg0NDg1NjMzNjY0/tent-repair.png',
          camperPrice: 1000,
          shelterPrice: 600,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'море',
          entertainment: 'прокат спортинвентаря, прокат пляжного инвенторя',
          communication: 'водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'городской округ Судак',
          pay_by_card: 'наличный, перевод',
          addition: 'Кемпинг у моря в Крыму, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг им. Владимира Дубинина',
          shelterCount: 10,
          camperCount: 20,
          eCoordinates: 34.43,
          wCoordinates: 44.67,
          data: `Приглашаем Вас отдохнуть в экологически чистом и романтическом месте у подножья гор. Шикарные виды на горы и море (до моря 500 метров по персональному спуску). Палаточные места в тени кипарисов и деревьев хвойных пород. Это волшебное место оборудовано всем необходимым.`,
          timeOpen: '06:00',
          timeClosed: '18:00',
          rate: 7,
          img:'http://crimea-media.ru/Dostop/South/Ayu_Doug/1B.jpg',
          img2: 'https://vsegda-pomnim.com/uploads/posts/2022-04/thumbs/1649993015_41-vsegda-pomnim-com-p-kemping-astra-ashe-foto-42.jpg',
          img3: 'https://na-more-v-crimea.ru/wp-content/uploads/2023/01/koronelli.jpg',
          camperPrice: 1200,
          shelterPrice: 1000,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'море',
          entertainment: 'прокат палатак',
          communication: 'водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'Комсомольская ул., 15, Алушта',
          pay_by_card: 'наличный, перевод',
          addition: 'Кемпинг у моря в Республике Крым, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг «Белая Русь»',
          shelterCount: 20,
          camperCount: 2,
          eCoordinates: 34.02,
          wCoordinates: 44.41,
          data: `Кемпинг «Белая Русь» — это отличное место для тех, кто хочет провести время на природе, наслаждаясь красивыми видами на горы и море.`,
          timeOpen: '07:00',
          timeClosed: '20:00',
          rate: 8,
          img:'https://sun9-27.userapi.com/impg/1Ir-HhM5M_zZlBXsuUm0uv6mTvwVGdSaiYCq7Q/pVGkezA0TAg.jpg?size=807x605&quality=95&sign=79c3477642eedb03ac951e8cd8d4d38e&c_uniq_tag=pA2VHXjfD4r2KNcYR7IGcAQPJedCwfUzuICWcgGTqeg&type=album',
          img2: 'https://sun9-71.userapi.com/impf/c847120/v847120300/a263e/wRNYNb17gfU.jpg?size=604x453&quality=96&sign=4b4fae8a935701e0c7d22f4e094dfc99&c_uniq_tag=jbcqQIy8lzOSdgIQpkn03wjMACyKUmuFjAy2lB1iux4&type=album',
          img3: 'https://sun9-46.userapi.com/c9776/u136688199/-6/z_c0f6effd.jpg',
          camperPrice: 5000,
          shelterPrice: 600,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'море',
          entertainment: 'прокат морского инвенторя, прокат лежаков с зонтиками',
          communication: 'водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'Южнобережный спуск, 3, Алупка',
          pay_by_card: 'наличный, перевод',
          addition: 'Кемпинг у моря в Республике Крым, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Дикая собака Динго',
          shelterCount: 20,
          camperCount: 1,
          eCoordinates: 49.05,
          wCoordinates: 55.69,
          data: `Настоящие приключения начинаются сдесь. Кемпинг расположен на строве, со всеми удобствами. Для отдыхаюшь есть места для кемпинга со своими палатками и так же места с бунгало.`,
          timeOpen: '08:00',
          timeClosed: '16:00',
          rate: 9,
          img:'https://avatars.mds.yandex.net/get-altay/4441655/2a000001804286f4afbc30bb7468749628dc/XL',
          img2: 'https://otdihvrossii.ru/wp-content/uploads/2017/07/11987.jpg',
          img3: 'https://avatars.mds.yandex.net/get-altay/6311095/2a0000018180a94fb61bb060fd0a2b42a7b1/XL',
          camperPrice: 5000,
          shelterPrice: 600,
          place_type: 'остров',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'прокат спортинвентаря, прокат лодок и катамаранов, детскач площадка, барбеку зона',
          communication: 'водопровод, свет, интернет',
          sanitation: 'туалет, душ, магазин',
          location: 'Весёлый остров, Республика Татарстан',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в пригороде Казань, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг "Глэмпинг Арт"',
          shelterCount: 20,
          camperCount: 20,
          eCoordinates: 48.54,
          wCoordinates: 54.24,
          data: `Глэмпинг «Арт» — это идеальное место для тех, кто хочет отдохнуть от городской суеты и насладиться тишиной и спокойствием. Гостям предлагается проживание в уютных домиках, оборудованных всем необходимым для комфортного отдыха.`,
          timeOpen: '07:00',
          timeClosed: '16:00',
          rate: 9,
          img:'https://vsegda-pomnim.com/uploads/posts/2022-04/thumbs/1648964939_41-vsegda-pomnim-com-p-kemping-v-lesu-foto-48.jpg',
          img2: 'https://avatars.mds.yandex.net/i?id=041941d6df98c6956fed44ac1b061fc45ea5300a-7682919-images-thumbs&n=13',
          img3: 'https://ekodome.com/wp-content/uploads/2022/12/American-Glamping-Association-Preferred-Partner-800x600.jpg',
          camperPrice: 1700,
          shelterPrice: 1200,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'прокат лодок и катамаранов',
          communication: 'водопровод, свет, интернет',
          sanitation: 'туалет, душ, магазин',
          location: 'Красный Яр, СНТ Сонечная поляна',
          pay_by_card: 'любой вид расчета',
          addition: 'Кемпинг на природе в Ульяновской области, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Кемпинг "Лесная сказка"',
          shelterCount: 20,
          camperCount: 10,
          eCoordinates: 46.29,
          wCoordinates: 51.78,
          data: `Кемпинг «Лесная сказка» расположен на берегу Волги и предлагает своим гостям комфортное проживание в палатках. На территории кемпинга есть оборудованная стоянка для автомобилей, бесплатный мангал и дрова, а также столы и лавочки для вечернего отдыха.`,
          timeOpen: '08:00',
          timeClosed: '16:00',
          rate: 9,
          img:'https://avatars.mds.yandex.net/get-altay/5965316/2a000001816bf1fd995721b8606d9b9b308b/XXXL',
          img2: 'https://avatars.mds.yandex.net/get-altay/5615085/2a0000018149200fc3cc6b9f9c506f2dae20/XXXL',
          img3: 'https://avatars.mds.yandex.net/get-altay/4432502/2a000001816bf1f134d37e4ed45d72fcc8fa/XXXL',
          camperPrice: 2500,
          shelterPrice: 1500,
          place_type: 'лес',
          seasonality: 'лето',
          reservoir: 'река',
          entertainment: 'детская площадка, рыбалка',
          communication: 'водопровод, свет',
          sanitation: 'туалет, душ',
          location: 'ул. Дачная, село Чардым',
          pay_by_card: 'наличный, перевод',
          addition: 'Кемпинг на природе в близи города Саратов, Россия',
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // {
        //   title: '',
        //   shelterCount: 20,
        //   camperCount: 20,
        //   eCoordinates: 39.86,
        //   wCoordinates: 42.42,
        //   data: ``,
        //   timeOpen: '00:00',
        //   timeClosed: '00:00',
        //   rate: 9,
        //   img:'',
        //   img2: '',
        //   img3: '',
        //   camperPrice: 600,
        //   shelterPrice: 600,
        //   place_type: 'лес',
        //   seasonality: 'лето',
        //   reservoir: 'нет',
        //   entertainment: 'прокат спортинвентаря',
        //   communication: 'водопровод, свет',
        //   sanitation: 'туалет, душ',
        //   location: 'хутов Каменный Брод',
        //   pay_by_card: 'наличный, перевод',
        //   addition: 'Кемпинг на природе в Ростовской области, Россия',
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Campers', null, {});
  },
};
