'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Routes',
      [
        {
          title:
            '«Князь Александр Невский». Автомобильный туристический маршрут',
          data: 'Маршрут объединяет места, связанные с именем Александра Невского и проходит по Ленинградской, Псковской и Новгородской области. Следуя по маршруту можно увидеть места легендарных битв, города, освобожденные и основанные князем.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/uploads/2022/11/rvland-knyaz-aleksandr-nevskii-3.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 5,
          km: 937,
        },
        {
          title: 'Ярославия. С автодомом по Ярославской области',
          data: 'Маршрут для путешествий с домом на колесах по Ярославской области. Ни одна территория России не может похвастаться таким количеством старинных, запоминающихся и живых городов. Каждый из которых обладает уникальным характером и имеет свой неповторимый образ.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/uploads/2022/03/rvland-yaroslaviya-2.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 5,
          km: 450,
        },
        {
          title: 'Первозданный север. Природные красоты Архангельской области',
          data: 'Маршрут для автотуристов, погрузит вас в мир уникальной природы русского севера и подарит незабываемые впечатления от соприкосновения с живописными уголками Архангельской области.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/uploads/2021/07/rvland-pervozdannyi-sever.-prirodnye-krasoty-arhangelskoi-oblasti-3.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 7,
          km: 800,
        },
        {
          title: 'Открытый север. Путешествуем по Архангельской области',
          data: 'Отправьтесь в путешествие по Архангельской области и прикоснитесь к богатой культуре и аутентичным традициям русского севера с нашим маршрутом по Поморью.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/uploads/2021/07/rvland-otkrytyi-sever.-puteshestvuem-po-arhangelskoi-oblasti-1600x900.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 5,
          km: 600,
        },
        {
          title: 'Путешествие по Московской и Калужской областям',
          data: 'Семидневный маршрут по Московской и Калужской области. Мелихово, Талеж, Приокско-Террасный заповедник, Серпухов, Таруса, Калуга, Полотняный завод, Арт-Парк Никола-Ленивец.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/uploads/2020/08/rvland-tihonova-pustin-02.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 7,
          km: 240,
        },
        {
          title: 'По Есенинским местам Рязанской области',
          data: 'Маршрут выходного дня по Есенинским местам Рязанской области: Зарайск, Константиново, Рязань, В некотором царстве.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/uploads/2020/10/rvland-esenin-route-06.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 3,
          km: 150,
        },
        {
          title: 'Путешествие через Алтай к Телецкому озеру',
          data: 'Путешествие с автодомом по Горному Алтаю подарит вам потрясающие виды заснеженных горных вершин, бескрайние хвойные леса, шумные водопады, неповторимую фауну и чистый воздух.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/uploads/2020/02/teleckoe-ozero.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 7,
          km: 1950,
        },
        {
          title: 'В Тулу со своим автодомом. Маршрут по Тульской области',
          data: 'Откройте для себя достопримечательности тульской области: старейший в кремль в России, музей оружия, Куликово поле и древние культовые объекты.',
          type: 'автодом',
          img: 'https://rvland.ru/wp-content/themes/rvl/graphics/defaults/route.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 2,
          km: 240,
        },
        {
          title: 'Из Москвы в Геленжин',
          data: 'Увлекеательное путишествие из города Москва в город Геленджик на автокемпинге. Потрясающие виды заснеженных горных вершин, бескрайние хвойные леса, шумные водопады, неповторимую фауну и чистый воздух.',
          type: 'автодом',
          img: 'https://vsegda-pomnim.com/uploads/posts/2022-04/1651021001_20-vsegda-pomnim-com-p-kemping-na-more-foto-24.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 3,
          km: 1540,
        },
        {
          title: 'Шатровый кемпинг из Судак в Ялту',
          data: 'Удивительное путишествие вдоль Черного моря по полуострову Крым. Ласковое море и не забываемые красоты полуострова не оставят вас от хорошего настроения и наполнят вас позитивной энергией на весь год.',
          type: 'палатки',
          img: 'https://sevastopol.su/sites/default/files/styles/node/public/2018-01-20/krym_turizm.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 5,
          km: 150,
        },
        {
          title: 'Шатровый кемпинг из Казань в Саратов в доль Волги',
          data: 'Путешествие от Казани до Саратова по берегу Волги - это увлекательный шатровый кемпинг с живописными островами, историческими городами и удивительными пейзажами. Путешествие, которое запомнится навсегда.',
          type: 'палатки',
          img: 'https://grkids.com/wp-content/uploads/2017/07/munising-tourist-park-campground.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 7,
          km: 642,
        },
        {
          title: 'Шатровый кемпинг',
          data: 'Если хотите окунуться в мир гармонии и духовного отдыха то вам обязательно надо опробовать этот маршрут!',
          type: 'палатки',
          img: 'https://nizhneivkinskoe-r43.gosweb.gosuslugi.ru/netcat_files/36/42/palatka_na_prirode_foto800.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
          days: 5,
          km: 200,
        },
        // {
        //   title: '',
        //   data: '',
        //   type: 'палатки',
        //   img: '',
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        //   days: 3,
        //   km: 500,
        // },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Routes', null, {});
  },
};
